import Head from 'next/head';

import Navigation from './navigation';
import Footer from './footer';

export const siteTitle = 'OptimalShipp';

function Layout({children}) {
  return (
    <div id="root">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />

      <main className="content">{children}</main>

      <Footer />
    </div>
  );
}

export default Layout;
